# Generated by Django 4.2.3 on 2023-08-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0002_advertisements_delete_onlineshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='User',
        ),
    ]
