# Generated by Django 4.2.3 on 2023-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0002_advertisements_delete_onlineshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisements',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default=1, upload_to='online_shop/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
